# StartUps.vet

### Quick Introduction

The following data sets have been scraped from `startups.vet/companies` and from `vip.vetbiz.gov/Public/Search/Default.aspx`. 

Both data sets require some cleaning up before they can be comfortably analyzed.

### Data

In [1]:
import pandas as pd

In [2]:
startups_data = pd.read_csv('../scanners/csv_files/startups_data.csv')

In [3]:
startups_data.head(5)

,Website,Employees,Total Funding,Stage,Year Founded,Organization Affiliation,Total Founders,Veteran Founders,Veteran Executives
0,AgentHero,NaN,k,NaN,2015,Patriot Boot Camp,NaN,NaN,True
1,Akouba Credit,NaN,k,NaN,2015,Bunker,NaN,NaN,True
2,Andela,NaN,k,NaN,2015,Patriot Boot Camp,NaN,NaN,True
3,"AuditPad, Inc.",2.0,k,NaN,2013,Patriot Boot Camp,2.0,1.0,True
4,"Avening Management and Technical Services, LLC",NaN,k,NaN,2012,Patriot Boot Camp,1.0,1.0,True

In [4]:
vetbiz_data = pd.read_csv('../scanners/csv_files/vetbiz_data.csv')

In [5]:
vetbiz_data.head(5)

,Duns,BusinessName,DbaName,City,State,Phone,CompanyEmail,WebSite,LastVerified,ExpirationDate,...,Naics,Fsc,Psc,GeographicalServiceArea,CommercialContracts,DodContracts,FSS,LastModified,MentorProtege,JointVenture
0,78705297,Eugene Robinson,Anadine Design Management,Buffalo,NY,7165636156,anadine51@yahoo.com,NaN,9/10/2015 12:00:00 AM,9/10/2017 12:00:00 AM,...,"236118, 236220, 237310, 238220, 238910, 238990...",NaN,NaN,NY,No,No,No,8/25/2016 9:20:39 AM,No,No
1,117941695,"DL Stone Enterprises, LLC",Stone Enterprises,Garden Ridge,TX,2106960919,sales@stonespecialties.com,stonespecialties.com,12/23/2015 12:00:00 AM,12/23/2017 12:00:00 AM,...,"313110, 314910, 315190, 315210, 315240, 316998...","7320, 7340, 8105, 8405, 8410, 8520",NaN,"AK, AL, AR, AZ, CA, CO, CT, DC, DE, FL, GA, HI...",Yes,No,No,2/6/2016 11:36:08 PM,No,No
2,961566031,"Friendship SDVB , LLC",NaN,Austin,TX,4798761012,friendshipco@mindspring.com,friendshipcompany1.com,12/10/2015 12:00:00 AM,12/10/2017 12:00:00 AM,...,"236220, 311991, 325120, 423420, 423430, 423990...",6830,NaN,XX,Yes,Yes,Yes,12/10/2015 1:07:04 PM,No,No
3,791265882,International Mortuary Shipping LLC,NaN,Union,SC,8644660100,sprow@charter.net,internationalmortuaryshipping.com,9/15/2016 12:00:00 AM,9/15/2018 12:00:00 AM,...,"812210, 812220",NaN,NaN,XX,No,No,No,9/15/2016 9:39:11 AM,No,No
4,808852177,(CMR) Services Inc.,NaN,Royse City,TX,3039013455,clayrankin79@gmail.com,NaN,5/18/2015 12:00:00 AM,5/18/2017 12:00:00 AM,...,"112111, 561611",NaN,"AA95, AB10","CO, TX",No,No,No,7/20/2015 12:59:42 PM,No,No